[project]
name = "firstpy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "nandinidhir22-sudo", email = "nandinidhir22@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "scikit-learn>=1.9.1",
]

[project.scripts]
firstpy = "firstpy:main"

[build-system]
requires = ["uv_build>=0.12.16,<0.13.0"]
build-backend = "uv_build"
